# golangci-lint configuration for lzctl
# https://golangci-lint.run/usage/configuration/
# Compatible with golangci-lint v2.x

version: "2"

run:
  timeout: 5m
  modules-download-mode: readonly

formatters:
  enable:
    - gofmt
    - goimports

linters:
  default: none
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused
    - ineffassign
    - misspell
    - revive
    - gosec
    - unconvert
    - unparam
    - prealloc
  settings:
    errcheck:
      check-type-assertions: true
      check-blank: false
      exclude-functions:
        # Safe to ignore: defer close/remove patterns
        - (*os.File).Close
        - (io.Closer).Close
        - os.Remove
        - os.Setenv
        - os.Unsetenv
        # Safe to ignore: styled terminal output — errors are best-effort UI
        - (*github.com/fatih/color.Color).Fprintf
        - (*github.com/fatih/color.Color).Fprintln
        - (*github.com/fatih/color.Color).Printf
        - (*github.com/fatih/color.Color).Println
        - (github.com/fatih/color.Color).Fprintf
        - (github.com/fatih/color.Color).Fprintln
        - fmt.Fprintln
        - fmt.Fprintf
        - fmt.Println
        - fmt.Printf
    govet:
      enable-all: true
      disable:
        - fieldalignment # too noisy
        - shadow         # intentional shadowing is common in Go error handling
        - unusedwrite    # noisy in test helpers
    revive:
      rules:
        - name: blank-imports
        - name: dot-imports
        - name: error-return
        - name: error-strings
        - name: exported
          disabled: true  # renaming public types is a breaking change
        - name: increment-decrement
        - name: var-naming
        - name: package-comments
          disabled: true
    misspell:
      locale: US
    gosec:
      excludes:
        - G104 # unhandled errors — covered by errcheck
        - G304 # file path from variable — expected in CLI tool

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - gosec
        - unparam
        - prealloc
    - path: cmd/
      linters:
        - unparam # cobra handlers have fixed signatures
  max-issues-per-linter: 50
  max-same-issues: 5
