# GoReleaser configuration for lzctl
# https://goreleaser.com/customization/

version: 2

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - id: lzctl
    binary: lzctl
    main: .
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X 'github.com/kjourdan1/lzctl/cmd.Version={{ .Version }}'
      - -X 'github.com/kjourdan1/lzctl/cmd.Commit={{ .ShortCommit }}'
      - -X 'github.com/kjourdan1/lzctl/cmd.BuildDate={{ .Date }}'
    flags:
      - -trimpath

archives:
  - id: default
    formats:
      - tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        formats:
          - zip
    files:
      - LICENSE
      - README.md
      - CHANGELOG.md

checksum:
  name_template: "checksums.txt"
  algorithm: sha256

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - "^docs:"
      - "^chore:"
      - "^ci:"
      - "^test:"
      - "^style:"
  groups:
    - title: "Features"
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: "Bug Fixes"
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: "Other"
      order: 999

release:
  github:
    owner: kjourdan1
    name: lzctl
  draft: false
  prerelease: auto
  name_template: "v{{ .Version }}"

# Homebrew tap publishing is configured separately via goreleaser-homebrew-tap action
# See: https://goreleaser.com/customization/homebrew/
