package template

import (
	"fmt"

	"github.com/kjourdan1/lzctl/internal/config"
)

func renderAVDBlueprintMainTF(cfg *config.LZConfig, zoneName string) string {
	slug := Slugify(zoneName)
	return fmt.Sprintf(`# Generated by lzctl blueprint catalog (avd-secure)
# --- Azure Virtual Desktop Secure Blueprint ---
terraform {
  required_version = ">= 1.5.0"
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "~> 3.100"
    }
  }
  backend "azurerm" {}
}

provider "azurerm" {
  features {}
}

data "terraform_remote_state" "management" {
  backend = "azurerm"
  config = {
    resource_group_name  = %q
    storage_account_name = %q
    container_name       = %q
    key                  = "platform-management.tfstate"
    subscription_id      = %q
    use_azuread_auth     = true
  }
}

# --- Resource Group ---
resource "azurerm_resource_group" "this" {
  name     = var.resource_group_name
  location = var.location
  tags     = var.tags
}

# --- User-Assigned Managed Identity (Entra ID join) ---
resource "azurerm_user_assigned_identity" "this" {
  name                = "mi-avd-%s"
  location            = azurerm_resource_group.this.location
  resource_group_name = azurerm_resource_group.this.name
  tags                = var.tags
}

# --- AVD Host Pool ---
resource "azurerm_virtual_desktop_host_pool" "this" {
  name                = "vdpool-%s"
  location            = azurerm_resource_group.this.location
  resource_group_name = azurerm_resource_group.this.name
  type                = "Pooled"
  load_balancer_type  = "BreadthFirst"
  validate_environment = false
  tags                = var.tags
}

# --- AVD Application Group ---
resource "azurerm_virtual_desktop_application_group" "this" {
  name                = "vdag-%s"
  location            = azurerm_resource_group.this.location
  resource_group_name = azurerm_resource_group.this.name
  type                = "Desktop"
  host_pool_id        = azurerm_virtual_desktop_host_pool.this.id
  tags                = var.tags
}

# --- AVD Workspace ---
resource "azurerm_virtual_desktop_workspace" "this" {
  name                = "vdws-%s"
  location            = azurerm_resource_group.this.location
  resource_group_name = azurerm_resource_group.this.name
  tags                = var.tags
}

resource "azurerm_virtual_desktop_workspace_application_group_association" "this" {
  workspace_id         = azurerm_virtual_desktop_workspace.this.id
  application_group_id = azurerm_virtual_desktop_application_group.this.id
}

# --- FSLogix Storage Account (Private Endpoint) ---
resource "azurerm_storage_account" "fslogix" {
  name                     = "stfslogix%s"
  location                 = azurerm_resource_group.this.location
  resource_group_name      = azurerm_resource_group.this.name
  account_tier             = "Premium"
  account_replication_type = "ZRS"
  account_kind             = "FileStorage"

  public_network_access_enabled = false
  min_tls_version               = "TLS1_2"
  tags                          = var.tags
}

resource "azurerm_storage_share" "fslogix" {
  name                 = "fslogix"
  storage_account_name = azurerm_storage_account.fslogix.name
  quota                = var.fslogix_share_quota_gb
}

# --- Private DNS Zone for Azure Files ---
resource "azurerm_private_dns_zone" "files" {
  name                = "privatelink.file.core.windows.net"
  resource_group_name = azurerm_resource_group.this.name
  tags                = var.tags
}

# --- Private Endpoint for FSLogix Storage ---
resource "azurerm_private_endpoint" "fslogix" {
  name                = "pe-fslogix-%s"
  location            = azurerm_resource_group.this.location
  resource_group_name = azurerm_resource_group.this.name
  subnet_id           = var.avd_subnet_id

  private_service_connection {
    name                           = "fslogix-private-link"
    private_connection_resource_id = azurerm_storage_account.fslogix.id
    subresource_names              = ["file"]
    is_manual_connection           = false
  }

  private_dns_zone_group {
    name                 = "fslogix-dns"
    private_dns_zone_ids = [azurerm_private_dns_zone.files.id]
  }

  tags = var.tags
}

# --- Diagnostic Settings (Log Analytics) ---
resource "azurerm_monitor_diagnostic_setting" "host_pool" {
  name                       = "diag-avd-%s"
  target_resource_id         = azurerm_virtual_desktop_host_pool.this.id
  log_analytics_workspace_id = data.terraform_remote_state.management.outputs.log_analytics_workspace_id

  enabled_log { category = "Checkpoint" }
  enabled_log { category = "Error" }
  enabled_log { category = "Management" }
  enabled_log { category = "Connection" }
  enabled_log { category = "HostRegistration" }
  enabled_log { category = "AgentHealthStatus" }
}
`,
		cfg.Spec.StateBackend.ResourceGroup,
		cfg.Spec.StateBackend.StorageAccount,
		cfg.Spec.StateBackend.Container,
		cfg.Spec.StateBackend.Subscription,
		slug, slug, slug, slug, slug, slug, slug,
	)
}

func renderAVDBlueprintVariablesTF() string {
	return `# Generated by lzctl blueprint catalog (avd-secure)
variable "location" {
  description = "Azure region for all resources."
  type        = string
}

variable "resource_group_name" {
  description = "Name of the resource group for the AVD deployment."
  type        = string
}

variable "avd_subnet_id" {
  description = "Subnet ID for session hosts and private endpoints."
  type        = string
}

variable "fslogix_share_quota_gb" {
  description = "Size in GB for the FSLogix file share."
  type        = number
  default     = 500
}

variable "tags" {
  description = "Tags applied to all resources."
  type        = map(string)
  default     = {}
}
`
}

func renderAVDBlueprintTFVars(cfg *config.LZConfig) string {
	return fmt.Sprintf(`# Generated by lzctl blueprint catalog (avd-secure)
location               = %q
resource_group_name    = "rg-avd-workload"
avd_subnet_id          = ""  # Set to the AVD session host subnet ID
fslogix_share_quota_gb = 500
tags = {
  managedBy   = "lzctl"
  environment = "production"
  tenant      = %q
}
`, cfg.Metadata.PrimaryRegion, cfg.Metadata.Tenant)
}
