package template

import (
	"fmt"

	"github.com/kjourdan1/lzctl/internal/config"
)

func renderACABlueprintMainTF(cfg *config.LZConfig, zoneName string) string {
	connectivityState := ConnectivityRemoteState(cfg)
	slug := Slugify(zoneName)
	return fmt.Sprintf(`# Generated by lzctl blueprint catalog (aca-platform)
# --- Container Apps Platform Blueprint ---
terraform {
  required_version = ">= 1.5.0"
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "~> 3.100"
    }
  }
  backend "azurerm" {}
}

provider "azurerm" {
  features {}
}

%s

# --- Resource Group ---
resource "azurerm_resource_group" "this" {
  name     = var.resource_group_name
  location = var.location
  tags     = var.tags
}

# --- User-Assigned Managed Identity ---
resource "azurerm_user_assigned_identity" "this" {
  name                = "mi-aca-%s"
  location            = azurerm_resource_group.this.location
  resource_group_name = azurerm_resource_group.this.name
  tags                = var.tags
}

# --- Key Vault (no public access) ---
module "key_vault" {
  source  = "Azure/avm-res-keyvault-vault/azurerm"
  version = "0.9.0"

  name                          = "kv-aca-%s"
  location                      = azurerm_resource_group.this.location
  resource_group_name           = azurerm_resource_group.this.name
  public_network_access_enabled = false
  soft_delete_retention_days    = 30

  role_assignments = {
    managed_identity = {
      role_definition_id_or_name = "Key Vault Secrets User"
      principal_id               = azurerm_user_assigned_identity.this.principal_id
    }
  }

  private_endpoints = {
    primary = {
      subnet_resource_id = data.terraform_remote_state.connectivity.outputs.workload_private_endpoint_subnet_id
    }
  }

  tags = var.tags
}

# --- Container Apps Environment (VNet injected) ---
resource "azurerm_container_app_environment" "this" {
  name                       = "cae-%s"
  location                   = azurerm_resource_group.this.location
  resource_group_name        = azurerm_resource_group.this.name
  infrastructure_subnet_id   = data.terraform_remote_state.connectivity.outputs.workload_private_endpoint_subnet_id
  internal_load_balancer_enabled = true
  tags                       = var.tags
}
`, connectivityState, slug, slug, slug)
}

func renderACABlueprintVariablesTF() string {
	return `# Generated by lzctl blueprint catalog (aca-platform)
variable "location" {
  description = "Azure region for all resources."
  type        = string
}

variable "resource_group_name" {
  description = "Name of the resource group for the Container Apps environment."
  type        = string
}

variable "tags" {
  description = "Tags applied to all resources."
  type        = map(string)
  default     = {}
}
`
}

func renderACABlueprintTFVars(cfg *config.LZConfig) string {
	return fmt.Sprintf(`# Generated by lzctl blueprint catalog (aca-platform)
location            = %q
resource_group_name = "rg-aca-workload"
tags = {
  managedBy   = "lzctl"
  environment = "production"
  tenant      = %q
}
`, cfg.Metadata.PrimaryRegion, cfg.Metadata.Tenant)
}
